# Generated by Django 5.1.2 on 2024-11-04 18:06

import datetime
import django.db.models.deletion
import student_desc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('deadline', models.DateField()),
                ('task', models.CharField(max_length=500)),
                ('penalty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('ST', 'Student'), ('TC', 'Teacher')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_desc.homework')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('answer', models.CharField(max_length=500)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_desc.homework')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_desc.user')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_desc.user', validators=[student_desc.models.validate_teacher]),
        ),
    ]
