# Generated by Django 5.1.2 on 2024-11-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_desc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
        migrations.RenameModel(
            old_name='ReadyTasks',
            new_name='ReadyTask',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='homework_id',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='readytask',
            old_name='homework_id',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='readytask',
            old_name='student_id',
            new_name='student',
        ),
    ]
