site_name: Описание лабораторных работ
nav:
 - Главная: index.md
 - Лабораторные работы:
   - Лабораторная работа 1: labs/lab_1.md
   - Лабораторная работа 2: labs/lab_2.md
   - Лабораторная работа 3: labs/lab_3.md
   - Лабораторная работа 4: labs/lab_4.md
theme:
 name: mkdocs