# Generated by Django 5.1.2 on 2024-11-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='own',
            name='name',
        ),
    ]
