# Generated by Django 5.1.2 on 2024-11-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_user_owner_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='passport_number',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
