# Generated by Django 5.1.2 on 2024-11-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_remove_owner_passport_number_delete_user'),
        ('project_first_app', '0009_remove_owner_passport_number_delete_user'),
    ]

    operations = [
    ]
